// Status
export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';

// Account
export const ACCOUNT_ON = 'ACCOUNT_ON';
export const ACCOUNT_OFF = 'ACCOUNT_OFF';
export const ACCOUNT_CHECK_REQUEST = 'ACCOUNT_CHECK_REQUEST';
export const ACCOUNT_CHECK_SUCCESS = 'ACCOUNT_CHECK_SUCCESS';
export const ACCOUNT_CHECK_FAILURE = 'ACCOUNT_CHECK_FAILURE';
export const ACCOUNT_REGISTER_REQUEST = 'ACCOUNT_REGISTER_REQUEST';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAILURE = 'ACCOUNT_REGISTER_FAILURE';
export const ACCOUNT_LOG_IN_REQUEST = 'ACCOUNT_LOG_IN_REQUEST';
export const ACCOUNT_LOG_IN_SUCCESS = 'ACCOUNT_LOG_IN_SUCCESS';
export const ACCOUNT_LOG_IN_FAILURE = 'ACCOUNT_LOG_IN_FAILURE';
export const ACCOUNT_LOG_OUT_REQUEST = 'ACCOUNT_LOG_OUT_REQUEST';
export const ACCOUNT_LOG_OUT_SUCCESS = 'ACCOUNT_LOG_OUT_SUCCESS';
export const ACCOUNT_LOG_OUT_FAILURE = 'ACCOUNT_LOG_OUT_FAILURE';
export const ACCOUNT_RESET_PASSWORD_REQUEST = 'ACCOUNT_RESET_PASSWORD_REQUEST';
export const ACCOUNT_RESET_PASSWORD_SUCCESS = 'ACCOUNT_RESET_PASSWORD_SUCCESS';
export const ACCOUNT_RESET_PASSWORD_FAILURE = 'ACCOUNT_RESET_PASSWORD_FAILURE';

// Profile
export const PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';
export const PROFILE_EDIT_FAILURE = 'PROFILE_EDIT_FAILURE';
export const PROFILE_STATUS_REQUEST = 'PROFILE_STATUS_REQUEST';
export const PROFILE_STATUS_SUCCESS = 'PROFILE_STATUS_SUCCESS';
export const PROFILE_STATUS_FAILURE = 'PROFILE_STATUS_FAILURE';
export const PROFILE_LOAD_REQUEST = 'PROFILE_LOAD_REQUEST';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_FAILURE = 'PROFILE_LOAD_FAILURE';
export const PROFILE_VOID = 'PROFILE_VOID';

// Call
export const CALLS_VOID = 'CALLS_VOID';

// User
export const USERS_LOAD_REQUEST = 'USERS_LOAD_REQUEST';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_FAILURE = 'USERS_LOAD_FAILURE';
export const USERS_WATCH_REQUEST = 'USERS_WATCH_REQUEST';
export const USERS_WATCH_SUCCESS = 'USERS_WATCH_SUCCESS';
export const USERS_WATCH_FAILURE = 'USERS_WATCH_FAILURE';
export const USERS_VOID = 'USERS_VOID';

// Champion
export const CHAMPIONS_LOAD_REQUEST = 'CHAMPIONS_LOAD_REQUEST';
export const CHAMPIONS_LOAD_SUCCESS = 'CHAMPIONS_LOAD_SUCCESS';
export const CHAMPIONS_LOAD_FAILURE = 'CHAMPIONS_LOAD_FAILURE';
export const CHAMPIONS_WATCH_REQUEST = 'CHAMPIONS_WATCH_REQUEST';
export const CHAMPIONS_WATCH_SUCCESS = 'CHAMPIONS_WATCH_SUCCESS';
export const CHAMPIONS_WATCH_FAILURE = 'CHAMPIONS_WATCH_FAILURE';
export const CHAMPIONS_VOID = 'CHAMPIONS_VOID';

// Composition
export const COMPOSITION_LOAD_REQUEST = 'COMPOSITION_LOAD_REQUEST';
export const COMPOSITION_LOAD_SUCCESS = 'COMPOSITION_LOAD_SUCCESS';
export const COMPOSITION_LOAD_FAILURE = 'COMPOSITION_LOAD_FAILURE';
export const COMPOSITION_BUILD_REQUEST = 'COMPOSITION_BUILD_REQUEST';
export const COMPOSITION_BUILD_SUCCESS = 'COMPOSITION_BUILD_SUCCESS';
export const COMPOSITION_BUILD_FAILURE = 'COMPOSITION_BUILD_FAILURE';
export const COMPOSITION_WATCH_REQUEST = 'COMPOSITION_WATCH_REQUEST';
export const COMPOSITION_WATCH_SUCCESS = 'COMPOSITION_WATCH_SUCCESS';
export const COMPOSITION_WATCH_FAILURE = 'COMPOSITION_WATCH_FAILURE';
export const COMPOSITION_VOID = 'COMPOSITION_VOID';
