// Account
export const ACCOUNT_ON = 'ACCOUNT_ON';
export const ACCOUNT_OFF = 'ACCOUNT_OFF';
export const ACCOUNT_CHECK_REQUEST = 'ACCOUNT_CHECK_REQUEST';
export const ACCOUNT_CHECK_SUCCESS = 'ACCOUNT_CHECK_SUCCESS';
export const ACCOUNT_CHECK_FAILURE = 'ACCOUNT_CHECK_FAILURE';
export const ACCOUNT_REGISTER_REQUEST = 'ACCOUNT_REGISTER_REQUEST';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAILURE = 'ACCOUNT_REGISTER_FAILURE';
export const ACCOUNT_LOG_IN_REQUEST = 'ACCOUNT_LOG_IN_REQUEST';
export const ACCOUNT_LOG_IN_SUCCESS = 'ACCOUNT_LOG_IN_SUCCESS';
export const ACCOUNT_LOG_IN_FAILURE = 'ACCOUNT_LOG_IN_FAILURE';
export const ACCOUNT_LOG_OUT_REQUEST = 'ACCOUNT_LOG_OUT_REQUEST';
export const ACCOUNT_LOG_OUT_SUCCESS = 'ACCOUNT_LOG_OUT_SUCCESS';
export const ACCOUNT_LOG_OUT_FAILURE = 'ACCOUNT_LOG_OUT_FAILURE';
export const ACCOUNT_RESET_PASSWORD_REQUEST = 'ACCOUNT_RESET_PASSWORD_REQUEST';
export const ACCOUNT_RESET_PASSWORD_SUCCESS = 'ACCOUNT_RESET_PASSWORD_SUCCESS';
export const ACCOUNT_RESET_PASSWORD_FAILURE = 'ACCOUNT_RESET_PASSWORD_FAILURE';

// Profile
export const PROFILE_LOAD_REQUEST = 'PROFILE_LOAD_REQUEST';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_FAILURE = 'PROFILE_LOAD_FAILURE';
export const PROFILE_VOID = 'PROFILE_VOID';

// Call
export const CALLS_VOID = 'CALLS_VOID';

// User
export const USERS_LOAD_REQUEST = 'USERS_LOAD_REQUEST';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_FAILURE = 'USERS_LOAD_FAILURE';
export const USERS_WATCH_SUCCESS = 'USERS_WATCH_SUCCESS';
export const USERS_WATCH_ERROR = 'USERS_WATCH_ERROR';
export const USERS_VOID = 'USERS_VOID';
