//Todo: move this to db later.
module.exports = {
    wildcardTank: {
        id: 'wildcardTank',
        key: 'Tank',
        name: 'Tank',
        role: 'tank',
        key: 'Tank',
        name: 'Tank',
        type: 'wildcard',
        order: 1,
    },
    wildcardMage: {
        id: 'wildcardMage',
        key: 'Mage',
        name: 'Mage',
        role: 'mage',
        key: 'Mage',
        name: 'Mage',
        type: 'wildcard',
        order: 2,
    },
    wildcardAssassin: {
        id: 'wildcardAssassin',
        key: 'Assassin',
        name: 'Assassin',
        role: 'assassin',
        key: 'Assassin',
        name: 'Assassin',
        type: 'wildcard',
        order: 3,
    },
    wildcardFighter: {
        id: 'wildcardFighter',
        key: 'Fighter',
        name: 'Fighter',
        role: 'fighter',
        key: 'Fighter',
        name: 'Fighter',
        type: 'wildcard',
        order: 4,
    },
    wildcardMarksman: {
        id: 'wildcardMarksman',
        key: 'Marksman',
        name: 'Marksman',
        role: 'marksman',
        key: 'Marksman',
        name: 'Marksman',
        type: 'wildcard',
        order: 5,
    },
    wildcardSupport: {
        id: 'wildcardSupport',
        key: 'Support',
        name: 'Support',
        role: 'support',
        key: 'Support',
        name: 'Support',
        type: 'wildcard',
        order: 6,
    },
};
